### ISSUE TITLE
Entity Security Role plugin crashes

### ISSUE THREAD

**Issue by rduz** [santoshCRM/EntitySecurityRole#1]
Hi,

XrmToolBox version is 1.2018.10.29.
EntitySecurityRole version is 1.2018.6.19

Entity Security Role is crashing.  At the time of the crash, I was working with a custom entity called "Rate Schedule (Commission)" and the focus was in the "Security Role" box.  I was using the up and down arrows to select security each security role to see what Teams and Users were assigned to said role.  When I select a role called "Email Template & Wholesaler Editing", the program crashes.  I suspect that the ampersand, being a special character in XML, is not properly escaped as "amp;"

Here is the crash log:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Xml.XmlException: An error occurred while parsing EntityName. Line 1, position 580.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseEntityName()
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlLoader.LoadNode(Boolean skipOverWhitespace)
   at System.Xml.XmlLoader.LoadDocSequence(XmlDocument parentDoc)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at EntitySecurityRole.Helper.CreateXml(String xml, String cookie, Int32 page, Int32 count)
   at EntitySecurityRole.Helper.getTeambySecurityRole(String SecurityRole, String buName)
   at EntitySecurityRole.EntitySecurityRole.lstview_sRole_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ListBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ListBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ListBox.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
XrmToolBox
    Assembly Version: 1.2018.10.29
    Win32 Version: 1.2018.10.29
    CodeBase: file:///C:/xrmtoolbox/XrmToolBox.exe
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
XrmToolBox.Extensibility
    Assembly Version: 1.2018.10.29
    Win32 Version: 1.2018.10.29
    CodeBase: file:///C:/xrmtoolbox/XrmToolBox.Extensibility.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.IdentityModel
    Assembly Version: 3.5.0.0
    Win32 Version: 6.1.7601.23675
    CodeBase: file:///C:/Windows/assembly/GAC_MSIL/Microsoft.IdentityModel/3.5.0.0__31bf3856ad364e35/Microsoft.IdentityModel.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
XrmToolBox.PluginsStore
    Assembly Version: 1.2018.10.29
    Win32 Version: 1.2018.10.29
    CodeBase: file:///C:/xrmtoolbox/XrmToolBox.PluginsStore.DLL
----------------------------------------
NuGet.Core
    Assembly Version: 2.14.0.832
    Win32 Version: 2.14.0.832
    CodeBase: file:///C:/xrmtoolbox/NuGet.Core.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 11.0.0.0
    Win32 Version: 11.0.2.21924
    CodeBase: file:///C:/xrmtoolbox/Newtonsoft.Json.DLL
----------------------------------------
McTools.Xrm.Connection
    Assembly Version: 1.2018.7.19
    Win32 Version: 1.2018.7.19
    CodeBase: file:///C:/xrmtoolbox/McTools.Xrm.Connection.DLL
----------------------------------------
McTools.Xrm.Connection.WinForms
    Assembly Version: 1.2018.7.19
    Win32 Version: 1.2018.7.19
    CodeBase: file:///C:/xrmtoolbox/McTools.Xrm.Connection.WinForms.DLL
----------------------------------------
Microsoft.Xrm.Sdk
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0002.0165
    CodeBase: file:///C:/xrmtoolbox/Microsoft.Xrm.Sdk.DLL
----------------------------------------
Microsoft.Xrm.Sdk.Workflow
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0002.0165
    CodeBase: file:///C:/xrmtoolbox/Microsoft.Xrm.Sdk.Workflow.DLL
----------------------------------------
Microsoft.Crm.Sdk.Proxy
    Assembly Version: 9.0.0.0
    Win32 Version: 9.0.0002.0165
    CodeBase: file:///C:/xrmtoolbox/Microsoft.Crm.Sdk.Proxy.DLL
----------------------------------------
Microsoft.Xrm.Tooling.Connector
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.931
    CodeBase: file:///C:/xrmtoolbox/Microsoft.Xrm.Tooling.Connector.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///C:/xrmtoolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL
----------------------------------------
Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms
    Assembly Version: 2.29.0.1078
    Win32 Version: 2.29.40822.1520
    CodeBase: file:///C:/xrmtoolbox/Microsoft.IdentityModel.Clients.ActiveDirectory.WindowsForms.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///C:/xrmtoolbox/WeifenLuo.WinFormsUI.Docking.DLL
----------------------------------------
WeifenLuo.WinFormsUI.Docking.ThemeVS2015
    Assembly Version: 3.0.4.0
    Win32 Version: 3.0.4.0
    CodeBase: file:///C:/xrmtoolbox/WeifenLuo.WinFormsUI.Docking.ThemeVS2015.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
McTools.StopAdvertisement
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/xrmtoolbox/McTools.StopAdvertisement.DLL
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.ComponentModel.Composition
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
AndyPopkin.BulkWorkflowExecution
    Assembly Version: 1.2017.7.21
    Win32 Version: 1.2017.7.21
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/ANDYPOPKIN.BULKWORKFLOWEXECUTION.DLL
----------------------------------------
Carfup.XTBPlugins.PersonalViewsMigration
    Assembly Version: 1.2018.6.5
    Win32 Version: 1.2018.6.5
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/CARFUP.XTBPLUGINS.PERSONALVIEWSMIGRATION.DLL
----------------------------------------
Cinteros.Xrm.XmlEditorUtils
    Assembly Version: 1.2016.4.106
    Win32 Version: 1.2016.4.106
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/CINTEROS.XRM.XMLEDITORUTILS.DLL
----------------------------------------
Cinteros.XTB.ViewDesigner
    Assembly Version: 1.2016.8.7
    Win32 Version: 1.2016.8.7
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/CINTEROS.XTB.VIEWDESIGNER.DLL
----------------------------------------
Colso.Xrm.DataTransporter
    Assembly Version: 1.2018.8.1
    Win32 Version: 1.2018.8.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/COLSO.XRM.DATATRANSPORTER.DLL
----------------------------------------
Cube.XRMToolBox.RecordCounter
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/CUBE.XRMTOOLBOX.RECORDCOUNTER.DLL
----------------------------------------
DamSim.SolutionTransferTool
    Assembly Version: 1.2018.10.9
    Win32 Version: 1.2018.10.9
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/DAMSIM.SOLUTIONTRANSFERTOOL.DLL
----------------------------------------
DamSim.ViewTransferTool
    Assembly Version: 1.2018.3.3
    Win32 Version: 1.2018.3.3
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/DAMSIM.VIEWTRANSFERTOOL.DLL
----------------------------------------
EntitySecurityRole
    Assembly Version: 1.2018.6.19
    Win32 Version: 1.2018.6.19
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/ENTITYSECURITYROLE.DLL
----------------------------------------
Javista.XrmToolBox.ImportNN
    Assembly Version: 1.2018.3.8
    Win32 Version: 1.2018.3.8
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/JAVISTA.XRMTOOLBOX.IMPORTNN.DLL
----------------------------------------
MsCrmTools.AccessChecker
    Assembly Version: 1.2018.7.2
    Win32 Version: 1.2018.7.2
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.ACCESSCHECKER.DLL
----------------------------------------
MsCrmTools.AssemblyRecoveryTool
    Assembly Version: 1.2018.3.2
    Win32 Version: 1.2018.3.2
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.ASSEMBLYRECOVERYTOOL.DLL
----------------------------------------
MsCrmTools.AttributeBulkUpdater
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.ATTRIBUTEBULKUPDATER.DLL
----------------------------------------
MscrmTools.AttributeUsageInspector
    Assembly Version: 1.2018.9.11
    Win32 Version: 1.2018.9.11
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.ATTRIBUTEUSAGEINSPECTOR.DLL
----------------------------------------
MsCrmTools.AuditCenter
    Assembly Version: 1.2016.9.1
    Win32 Version: 1.2016.9.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.AUDITCENTER.DLL
----------------------------------------
MsCrmTools.ChartManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.CHARTMANAGER.DLL
----------------------------------------
MscrmTools.CrmTraceReader
    Assembly Version: 1.2018.4.1
    Win32 Version: 1.2018.4.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.CRMTRACEREADER.DLL
----------------------------------------
MsCrmTools.DocumentTemplatesMover
    Assembly Version: 1.2018.4.3
    Win32 Version: 1.2018.4.3
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.DOCUMENTTEMPLATESMOVER.DLL
----------------------------------------
MsCrmTools.FetchXmlTester
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.FETCHXMLTESTER.DLL
----------------------------------------
MsCrmTools.FlsBulkUpdater
    Assembly Version: 1.2016.12.1
    Win32 Version: 1.2016.12.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.FLSBULKUPDATER.DLL
----------------------------------------
MsCrmTools.FormRelated
    Assembly Version: 1.2017.12.3
    Win32 Version: 1.2017.12.3
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.FORMRELATED.DLL
----------------------------------------
MsCrmTools.Iconator
    Assembly Version: 1.2018.7.9
    Win32 Version: 1.2018.7.9
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.ICONATOR.DLL
----------------------------------------
MscrmTools.ManagedSolutionDeletionTool
    Assembly Version: 1.2016.11.1
    Win32 Version: 1.2016.11.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.MANAGEDSOLUTIONDELETIONTOOL.DLL
----------------------------------------
MsCrmTools.MetadataBrowser
    Assembly Version: 1.2018.12.11
    Win32 Version: 1.2018.12.11
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.METADATABROWSER.DLL
----------------------------------------
MsCrmTools.MetadataDocumentGenerator
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.METADATADOCUMENTGENERATOR.DLL
----------------------------------------
MscrmTools.PortalCodeEditor
    Assembly Version: 1.2018.6.8
    Win32 Version: 1.2018.6.8
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.PORTALCODEEDITOR.DLL
----------------------------------------
MscrmTools.PortalRecordsMover
    Assembly Version: 1.2018.6.5
    Win32 Version: 1.2018.6.5
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.PORTALRECORDSMOVER.DLL
----------------------------------------
MsCrmTools.SampleTool
    Assembly Version: 1.2018.6.23
    Win32 Version: 1.2018.6.23
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SAMPLETOOL.DLL
----------------------------------------
MsCrmTools.ScriptsFinder
    Assembly Version: 1.2018.9.8
    Win32 Version: 1.2018.9.8
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SCRIPTSFINDER.DLL
----------------------------------------
MsCrmTools.SecurityRelated
    Assembly Version: 1.2018.9.3
    Win32 Version: 1.2018.9.3
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SECURITYRELATED.DLL
----------------------------------------
MsCrmTools.SiteMapEditor
    Assembly Version: 1.2018.7.11
    Win32 Version: 1.2018.7.11
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SITEMAPEDITOR.DLL
----------------------------------------
MsCrmTools.SolutionComponentsMover
    Assembly Version: 1.2016.6.3
    Win32 Version: 1.2016.6.3
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SOLUTIONCOMPONENTSMOVER.DLL
----------------------------------------
MsCrmTools.SolutionImport
    Assembly Version: 1.2016.8.23
    Win32 Version: 1.2016.8.23
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SOLUTIONIMPORT.DLL
----------------------------------------
MscrmTools.SyncFilterManager
    Assembly Version: 1.2017.3.1
    Win32 Version: 1.2017.3.1
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.SYNCFILTERMANAGER.DLL
----------------------------------------
MsCrmTools.Translator
    Assembly Version: 1.2018.4.6
    Win32 Version: 1.2018.4.6
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.TRANSLATOR.DLL
----------------------------------------
MsCrmTools.UserSettingsUtility
    Assembly Version: 1.2018.7.8
    Win32 Version: 1.2018.7.8
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.USERSETTINGSUTILITY.DLL
----------------------------------------
MsCrmTools.ViewLayoutReplicator
    Assembly Version: 1.2017.4.4
    Win32 Version: 1.2017.4.4
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.VIEWLAYOUTREPLICATOR.DLL
----------------------------------------
MscrmTools.WebresourcesManager
    Assembly Version: 2.2019.1.6
    Win32 Version: 2.2019.1.6
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/MSCRMTOOLS.WEBRESOURCESMANAGER.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities.Tooling
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.TOOLING.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities.Xrm
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.XRM.DLL
----------------------------------------
Norriq.XrmToolBox.Facilities.Xrm.Tooling
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/NORRIQ.XRMTOOLBOX.FACILITIES.XRM.TOOLING.DLL
----------------------------------------
Norriq.XrmToolBox.YourUserSecurityMagnified
    Assembly Version: 1.0.18152.13
    Win32 Version: 1.0.18152.13
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/NORRIQ.XRMTOOLBOX.YOURUSERSECURITYMAGNIFIED.DLL
----------------------------------------
Personalview
    Assembly Version: 1.2017.7.14
    Win32 Version: 1.2017.7.14
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/PERSONALVIEW.DLL
----------------------------------------
Rappen.XTB.FXB
    Assembly Version: 1.2018.12.5
    Win32 Version: 1.2018.12.005
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/RAPPEN.XTB.FXB.DLL
----------------------------------------
TomasSchulkes.XrmToolbox.RecordOpenerPlugin
    Assembly Version: 1.2017.10.31
    Win32 Version: 1.2017.10.31
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/TOMASSCHULKES.XRMTOOLBOX.RECORDOPENERPLUGIN.DLL
----------------------------------------
UserTeamSecurityRoleReporter
    Assembly Version: 1.2018.4.6
    Win32 Version: 1.2018.04.06
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/USERTEAMSECURITYROLEREPORTER.DLL
----------------------------------------
XrmToolbox.JavascriptValidator
    Assembly Version: 1.0.0.3
    Win32 Version: 1.0.0.3
    CodeBase: file:///C:/XRMTOOLBOX/DATA/PLUGINS/XRMTOOLBOX.JAVASCRIPTVALIDATOR.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Web
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3282.0 built by: NET472REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Web/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.dll
----------------------------------------
System.Design
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Design/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Design.dll
----------------------------------------
WindowsBase
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll
----------------------------------------
PresentationFramework
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll
----------------------------------------
PresentationCore
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll
----------------------------------------
System.Xaml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3362.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll
----------------------------------------
MetadataViewProxies_d1c8d8eb-e165-4021-95f9-cdcbe0558427
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3062.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
SMDiagnostics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/SMDiagnostics/v4.0_4.0.0.0__b77a5c561934e089/SMDiagnostics.dll
----------------------------------------
System.ServiceModel.Internals
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Internals/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Internals.dll
----------------------------------------
System.ServiceModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel/v4.0_4.0.0.0__b77a5c561934e089/System.ServiceModel.dll
----------------------------------------
System.Web.Services
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Services/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Web.Services.dll
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System.Deployment
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
Microsoft.VisualStudio.Diagnostics.ServiceModelSink
    Assembly Version: 4.0.0.0
    Win32 Version: 14.0.23107.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Diagnostics.ServiceModelSink/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Diagnostics.ServiceModelSink.dll
----------------------------------------
System.ServiceModel.Channels
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ServiceModel.Channels/v4.0_4.0.0.0__31bf3856ad364e35/System.ServiceModel.Channels.dll
----------------------------------------
System.IdentityModel
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3260.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.IdentityModel.Selectors
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3062.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IdentityModel.Selectors/v4.0_4.0.0.0__b77a5c561934e089/System.IdentityModel.Selectors.dll
----------------------------------------
System.Security
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by rduz** [comment]
Pardon, I meant to say that the & character should be escaped to &amp;

Ok, the editor is mangling the comment.

![image](https://user-images.githubusercontent.com/956908/53904722-5583d880-400c-11e9-8a46-2f616077e0a9.png)

**Comment by santoshCRM** [comment]
Hi rduz,
Thanks for your feedback. Currently busy in some projects. Once get some will sure check this scenerio.
